Repository dsomni/accept_front, pull requests merged in 2023-01, with the labels that each got.

#101 Multiline text fix
  pages/task/tests/[spec].tsx
  src/components/Task/Description/Description.tsx
  src/components/Task/Description/description.module.css
  src/components/Task/Form/Examples/Examples.tsx
  src/components/Task/Form/Tests/Tests.tsx
  src/components/ui/ListItem/ListItem.tsx
  src/utils/openText.ts
Labels: styles

#106 Change project version
  package.json
  src/components/MainPage/TopContent/TopContent.tsx
Labels: styles

#108 Fix [russian locale] choose verb
  src/locale/ru/assignment/form/index.ts
  src/locale/ru/assignment/form/validation.ts
  src/locale/ru/assignmentSchema/form/index.ts
  src/locale/ru/auth/errors.ts
  src/locale/ru/form.ts
  src/locale/ru/notification/form/validate.ts
  src/locale/ru/tournament/form/index.ts
  src/locale/ru/ui/codeArea.ts
Labels: bug

#109 UserSelector separate "view profile" button
  ckeditor5-custom/build/ckeditor.js
  middleware.ts
  next.config.js
  package.json
  pages/403.tsx
  pages/404.tsx
  pages/500.tsx
  pages/_error.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  pages/task/[spec]/index.tsx
  src/components/Attempt/Info/Info.tsx
  src/components/Dashboard/AttemptsList/AttemptsList.tsx
  src/components/Dashboard/ParticipantsList/ParticipantsList.tsx
  src/components/Dashboard/ParticipantsList/ParticipantsListWithBan.tsx
  src/components/Dashboard/TimeInfo/TimeInfo.tsx
  src/components/MainPage/TopContent/TopContent.tsx
  src/components/Profile/AttemptListProfile/AttemptListProfile.tsx
  src/components/Task/DeleteModal/DeleteModal.tsx
  src/components/Todo/Todo.tsx
  src/components/layout/Navbar/Logo/Logo.tsx
  src/components/ui/ResultsTable/DropdownList/DropdownList.tsx
  src/components/ui/ResultsTable/ResultsTable.tsx
  src/components/ui/TasksBar/TasksBar.tsx
  src/components/ui/Timer/Timer.tsx
  src/components/ui/selectors/AssignmentSchemaSelector/AssignmentSchemaSelector.tsx
  src/components/ui/selectors/UserSelector/UserSelector.tsx
  src/components/ui/selectors/UserSelector/userSelector.module.css
  src/layouts/LoginLayout.tsx
  yarn.lock
Labels: bug

#110 Revalidation time refactor
  pages/attempt/[spec].tsx
  pages/dashboard/assignment/[spec].tsx
  pages/dashboard/tournament/[spec].tsx
  pages/edu/assignment/[spec]/index.tsx
  pages/edu/assignment/add.tsx
  pages/edu/assignment/edit/[spec]/index.tsx
  pages/edu/assignment_schema/[spec]/index.tsx
  pages/edu/assignment_schema/edit/[spec].tsx
  pages/group/edit/[spec].tsx
  pages/task/[spec]/index.tsx
  pages/task/edit/[spec]/index.tsx
  pages/task/tests/[spec].tsx
  pages/tournament/add.tsx
  pages/tournament/edit/[spec].tsx
  src/components/AssignmentSchema/Form/Form.tsx
  src/constants/PageRevalidation.ts
Labels: refactor

#114 Fix preview size
  src/components/AssignmentSchema/Form/Preview/Preview.tsx
  src/components/Task/Form/Preview/Preview.tsx
  src/components/Tournament/Form/Preview/Preview.tsx
Labels: bug, styles

#124 Feature/initiate chat
  pages/api/assignment/bundle-participants/[spec].tsx
  pages/api/assignment/participats/list/[spec].ts
  pages/api/tournament/bundle-participants/[spec].tsx
  pages/api/tournament/participants/list/[spec].ts
  src/components/Dashboard/AssignmentDashboard.tsx
  src/components/Dashboard/ChatPage/ChatPage.tsx
  src/components/Dashboard/ChatPage/InitiateChatModal/InitiateChatModal.tsx
  src/components/Dashboard/ChatPage/InitiateChatModal/MemberSelector/MemberSelector.tsx
  src/components/Dashboard/ChatPage/InitiateChatModal/MemberSelector/memberSelector.module.css
  src/components/Dashboard/ChatPage/InitiateChatModal/initiateChatModal.module.css
  src/components/Dashboard/ChatPage/chatPage.module.css
  src/components/Dashboard/ParticipantsList/ParticipantsList.tsx
  src/components/Dashboard/ParticipantsList/ParticipantsListWithBan.tsx
  src/components/Dashboard/TournamentDashboard.tsx
  src/components/ui/Chat/Chat.tsx
  src/components/ui/Chat/chat.module.css
  src/components/ui/ChatSticky/ChatSticky.tsx
  src/components/ui/selectors/UserSelect/UserSelect.tsx
  src/components/ui/selectors/UserSelect/userSelect.module.css
  src/components/ui/selectors/index.ts
  src/hooks/useBackNotifications.tsx
  src/locale/en/dashboard/chat.ts
  src/locale/en/dashboard/index.ts
  src/locale/ru/dashboard/chat.ts
  src/locale/ru/dashboard/index.ts
  src/utils/createSocket.ts
Labels: bug, assignment, tournament, new feature

#125 Feature/empty notification list
  src/components/Notification/List/NotificationList.tsx
  src/components/Notification/List/notificationList.module.css
  src/locale/en/profile/index.ts
  src/locale/ru/profile/index.ts
Labels: notification, profile

#127 New profile statistics
  pages/profile/[login]/index.tsx
  pages/profile/me.tsx
  src/components/Profile/AssignmentList/AssignmentList.tsx
  src/components/Profile/Profile.tsx
  src/components/Profile/ProfileInfo/AttemptInfo/AttemptInfo.tsx
  src/components/Profile/ProfileInfo/AttemptInfo/attemptInfo.module.css
  src/components/Profile/ProfileInfo/GroupsInfo/GroupsInfo.tsx
  src/components/Profile/ProfileInfo/GroupsInfo/groupsInfo.module.css
  src/components/Profile/ProfileInfo/MainInfo/MainInfo.tsx
  src/components/Profile/ProfileInfo/MainInfo/mainInfo.module.css
  src/components/Profile/ProfileInfo/ProfileInfo.tsx
  src/components/Profile/ProfileInfo/ShortStatistics/ShortStatistics.tsx
  src/components/Profile/ProfileInfo/ShortStatistics/shortStatistics.module.css
  src/components/Profile/ProfileInfo/TaskInfo/TaskInfo.tsx
  src/components/Profile/ProfileInfo/TaskInfo/taskInfo.module.css
  src/components/Profile/ProfileInfo/profileInfo.module.css
  src/components/ui/Plot/BarPiePlot/BarPiePlot.tsx
  src/components/ui/Plot/BarPiePlot/barPiePlot.module.css
  src/components/ui/Plot/BarPlot/Bar/Bar.tsx
  src/components/ui/Plot/BarPlot/Bar/bar.module.css
  src/components/ui/Plot/BarPlot/BarPlot.tsx
  src/components/ui/Plot/BarPlot/barPlot.module.css
  src/components/ui/Plot/PiePlot/Arc/Arc.tsx
  src/components/ui/Plot/PiePlot/Arc/arc.module.css
  src/components/ui/Plot/PiePlot/DefaultCentralText/DefaultCentralText.tsx
  src/components/ui/Plot/PiePlot/DefaultCentralText/defaultCentralText.module.css
  src/components/ui/Plot/PiePlot/PiePlot.tsx
  src/components/ui/Plot/PiePlot/piePlot.module.css
  src/components/ui/Plot/PlotTooltip/PlotTooltip.tsx
  src/components/ui/Plot/PlotTooltip/plotTooltip.module.css
  src/components/ui/Plot/index.ts
  src/constants/Colors.ts
  src/locale/en/index.ts
  src/locale/en/profile/index.ts
  src/locale/en/profile/info.ts
  src/locale/ru/index.ts
  src/locale/ru/profile/index.ts
  src/locale/ru/profile/info.ts
  src/types/data/IProfileInfo.ts
  src/types/ui/IPlot.ts
  styles/profile/login.module.css
Labels: profile, new feature

#129 Fix links on rating page
  pages/rating.tsx
Labels: bug, styles

#133 Add [big tests validation] Task/Form
  src/components/Task/Form/Form.tsx
  src/components/Task/Form/Tests/Tests.tsx
  src/components/ui/basics/Dropzone/Dropzone.tsx
  src/locale/en/task/form/validation.ts
  src/locale/en/ui/codeArea.ts
  src/locale/en/ui/dropzone.ts
  src/locale/en/ui/index.ts
  src/locale/ru/task/form/validation.ts
  src/locale/ru/ui/codeArea.ts
  src/locale/ru/ui/dropzone.ts
  src/locale/ru/ui/index.ts
Labels: task

#137 Bugfix styles and locales
  src/components/Task/DeleteModal/DeleteModal.tsx
  src/components/ui/basics/Dropzone/Dropzone.tsx
  src/locale/en/contacts.ts
  src/locale/en/profile/info.ts
  src/locale/ru/contacts.ts
  src/locale/ru/profile/info.ts
Labels: styles
