Repository dsomni/accept_front, pull requests merged in 2023-04, with the labels that each got.

#169 Release 2.2.1
  package.json
  src/components/Dashboard/Results/Results.tsx
Labels: bug

#171 Release 2.2.2
  package.json
  src/components/Dashboard/Results/Results.tsx
Labels: release

#180 Fix/tournament timer
  src/components/Dashboard/AssignmentDashboard.tsx
  src/components/Dashboard/TimeInfo/TimeInfo.tsx
  src/components/Dashboard/TournamentDashboard.tsx
  src/components/ui/Timer/Timer.tsx
  src/components/ui/Timer/timer.module.css
  src/hooks/useRequest.tsx
  src/locale/en/notify/tournament.ts
  src/locale/ru/notify/tournament.ts
Labels: assignment, tournament, time

#183 Improve verdict messages
  pages/task/list.tsx
  src/components/Attempt/Info/Info.tsx
  src/components/Dashboard/AttemptsList/AttemptsList.tsx
  src/components/Dashboard/TaskList/TaskList.tsx
  src/components/Profile/AttemptListProfile/AttemptListProfile.tsx
  src/components/Task/Results/Results.tsx
  src/components/ui/AttemptList/AttemptList.tsx
  src/components/ui/PrimitiveTaskTable/PrimitiveTaskTable.tsx
  src/components/ui/VerdictWrapper/VerdictWrapper.tsx
  src/components/ui/VerdictWrapper/verdictWrapper.module.css
  src/locale/en/index.ts
  src/locale/ru/index.ts
Labels: refactor, attempt

#189 Release 2.2.4
  package.json
  pages/api/task/my.ts
  pages/tournament/[spec].tsx
  src/components/Dashboard/ChatPage/ChatPage.tsx
  src/components/Dashboard/ChatPage/InitiateChatModal/InitiateChatModal.tsx
  src/components/Dashboard/ChatPage/chatPage.module.css
  src/components/Profile/AttemptListProfile/AttemptListProfile.tsx
  src/components/ui/AttemptList/AttemptList.tsx
  src/components/ui/VerdictWrapper/VerdictWrapper.tsx
  src/components/ui/basics/TextInput/TextInput.tsx
Labels: bug, styles, release
